"""
STEP File Fitting Import System

This module provides tools to import manufacturer-provided STEP files as fittings
in pypegen with proper port and attachment point definitions.

Three approaches are supported:
1. CAD Marker Detection - Auto-detect PORT_* coordinate systems from STEP files
2. CLI Helper Tool - Guided workflow for defining ports interactively
3. Configuration File - YAML format (generated by above tools, or hand-edited)
"""

from .config_schema import (
    AttachmentPointConfig,
    FittingConfig,
    FittingLibraryConfig,
    OrientationConfig,
    PortConfig,
    TransformConfig,
)
from .fitting_loader import FittingLoader
from .marker_detector import DetectedMarker, StepMarkerDetector

__all__ = [
    # Config schema
    "FittingLibraryConfig",
    "FittingConfig",
    "PortConfig",
    "AttachmentPointConfig",
    "OrientationConfig",
    "TransformConfig",
    # Marker detection
    "StepMarkerDetector",
    "DetectedMarker",
    # Fitting loader
    "FittingLoader",
]
